server:
  port: 9701
spring:
  application:
    name: feign-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9999/eureka/
feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix
logging:
  level:
    com.study.feign.service.UserService: debug