server:
  port: 9901
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9999/eureka/
zuul:
  routes:   #给服务配置路由
    user-service:
      path: /feignService/**
    feign-service:
      path: /feignService/**
#  ignored-services: user-service,feign-service   #关闭默认路由配置
#  prefix: /proxy  #给网关路由添加前缀    需要在访问地址前添加http://localhost:9901/proxy/user-service/user/1 才能访问到user-service中的接口
  sensitive-headers: Cookie,Set-Cookie,Authorization  #配置过滤敏感的请求头信息，设置为空就不会过滤。 防止路由时Cookie及Authorization的丢失
  add-host-header: true  #设置为true重定向是会添加host请求头
  PreLogFilter:
    pre:
      disable: true  #控制是否启用过滤器
management:
  endpoints:
    web:
      exposure:
        include: 'routes'       #开启查看路由的端点
