server:
  port: 9402
spring:
  application:
    name: hystrix-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user-service
service-url:
  user-service: http://user-service
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'  #暴露hystrix监控端点