server:
  port: 8080
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8081/eureka-server
  server:
    enable-self-preservation: false

