server:
  port: 8081
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8080/eureka-server
  server:
    enable-self-preservation: false